### ISSUE TITLE
Replace applicationId by appId

### ISSUE THREAD

**Issue by Jerskouille** [algolia/algoliasearch-zendesk#26]
For consistency with instantsearch.js usage.

![instantsearch's usage](https://cloud.githubusercontent.com/assets/5095856/11981698/55b15694-a9a5-11e5-9716-7daa90da9848.PNG)

**Comment by redox** [comment]
Actually, I was about creating an issue on `instantsearch.js` because we use `applicationId` everywhere else :/

**Comment by Jerskouille** [comment]
OK for me to use either of them, as long as it's the same one everywhere. :)
