### ISSUE TITLE
Create a search API key targetting only these indices

### ISSUE THREAD

**Issue by Jerska** [algolia/algoliasearch-zendesk#43]
And display it in the code block.
Right now, we're giving the public search API key, which should be good in most cases, but might be an attack vector if used for other indices. (`GenerateSecuredAPIKey` for instance)

**Comment by redox** [comment]
I would go for a dedicated API key then @Jerskouille, not a secured api key. So you can include a small description & be sure the user won't remove the underlying API key.

**Comment by Jerskouille** [comment]
That's what I meant, I was thinking about the `securedApiKey` as a type of key that would get compromised if the main search API key leaked.
