### ISSUE TITLE
Allow protocol with input

### ISSUE THREAD

**Issue by LukyVj** [algolia/algoliasearch-zendesk#52]
If a user want to put his protocol ( both `http://` or `https://` ) in the input, it will fail. 
![](http://puu.sh/ptpS4/e328d947c5.png)

It would be cool to allow the user to use the protocol he wants, without popping a frustrating error, using a different regex.

**Comment by Jerskouille** [comment]
Basically, let's extend that to `anything<ZendeskSubdomainRegexp>.zendesk.com<anything>`

**Comment by Jerskouille** [comment]
Done in https://github.com/algolia/AlgoliaWeb/commit/4d4fde7318a4d26b461fc4130417ac6a6fbdce6c .
