### ISSUE TITLE
Add a way to assign tags to languages

### ISSUE THREAD

**Issue by Jerskouille** [algolia/algoliasearch-zendesk#58]
Zendesk doesn't provide a way to have tags per language. Since we're displaying them publicly, we should provide a way for our users to have tags per language.

A syntax like `locale:tag` would probably do the trick. We  would still index tags without the delimiter for all translations.

**Comment by redox** [comment]
Looks good 👍 

I'm sure there is no way someone has a regular tag starting by a locale + `:` so we can even deploy it in a minor release 👍

**Comment by Jerskouille** [comment]
Done with https://github.com/algolia/algoliasearch-zendesk/compare/v2.7.0...v2.8.0 .
