### ISSUE TITLE
Uncaught ReferenceError: algoliasearchZendeskHC is not defined(…)

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-zendesk#61]
With my adblocker, because it blocks the load of `http://help.<WEBSITE>.com/hc/tracking/events?locale=en-us` our JS script seems not to be loaded.

Not sure if there is a way to improve that.

**Comment by Jerskouille** [comment]
Are you blocked on every support website you're visiting? What adblocker and lists are you using?

**Comment by redox** [comment]
It's uBlock Origin. Fun thing is that it's not everywhere. I think it depends if the error my ad blocker triggered is before or after or snippet. Not sure if we can do anything except asking them to put our code at the very top?

**Comment by Jerskouille** [comment]
After checking directly with redox, it was a domain related issue, closing.
