### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by LucasC** [algolia/algoliasearch-zendesk#63]
Issue reported on the community forum: https://discourse.algolia.com/t/zendesk-bug-pagination/165

Can be verified on our demo: https://algolia-test.zendesk.com/hc/en-us/search?query=a&hPP=20&idx=zendesk_algolia-test_articles&p=0&fR%5Blocale.locale%5D%5B0%5D=en-us&hFR%5Bcategory.title%5D%5B0%5D=FAQ&utf8=%E2%9C%93&commit=Search&is_v=1

(I also reproduce it on other live HC).

**Comment by Jerskouille** [comment]
Resolved with https://github.com/algolia/algoliasearch-zendesk/commit/0ba3e0b6501f5c701a7f840d9d9787916311d339
