### ISSUE TITLE
Uncaught ReferenceError: algoliasearchZendeskHC is not defined

### ISSUE THREAD

**Issue by ehubbell** [algolia/algoliasearch-zendesk#69]
I'm getting the following error message when I load our help center and it seems to have broke Algolia Search on every page. 

`Uncaught ReferenceError: algoliasearchZendeskHC is not defined`

You can checkout our help center here: support.myhubapp.com

I had Algolia search working a couple weeks ago but it kinda just stopped working. I checked the documentation on the setup page, and the code it gives me is exactly what I have copied in our document head file (see below)

```
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/algoliasearch.zendesk-hc/2/algoliasearch.zendesk-hc.min.css">
<script type="text/javascript" src="//cdn.jsdelivr.net/algoliasearch.zendesk-hc/2/algoliasearch.zendesk-hc.min.js"></script>
<script type="text/javascript">
  algoliasearchZendeskHC({
    applicationId: 'BHB2E3F079',
    apiKey: '2f24626640119d95987a5c8c47aafd79',
    subdomain: 'myhubapp'
  });
</script>
```

Any ideas what's going on here? Do I need to be signed up for a paid plan? Or, did you change one of the URLs?

**Comment by Glioburd** [comment]
Same problem here, I've an error message
```eferenceError: algoliasearch is not defined``` for the line
```var client = algoliasearch("QG4ODB2KKN", "ba034a019138ccc306f213e517e79e88");```

I cannot search on my algolia index anymore. It seems he doesn't "recognize" algoliasearch anmore.

**Comment by ehubbell** [comment]
This was my own fault. Was missing a `</script>` end tag at the end of some code above the Algolia script. Was difficult to troubleshoot without JSHint!
