### ISSUE TITLE
Articles switched from private to public are not indexed

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-zendesk#75]
Hi, following a support request on support@algolia.com, it seems that articles that were initially created private and then declared as public are not indexed by the connector.

Let me know if we can fix that for our customers.

**Comment by Jerska** [comment]
I believe this is fixed by https://github.com/algolia/algoliasearch-zendesk/commit/bec8eccb8822b0182003333c65267283cb65210d
