### ISSUE TITLE
Add support for the analytics boolean

### ISSUE THREAD

**Issue by YesThatAllen** [algolia/algoliasearch-zendesk#76]
Building on the topic in the community at: https://discourse.algolia.com/t/exclude-logged-in-agents-from-zendesk-search-results/6047

The request here is to add support for `analytics` here:

```
algoliasearchZendeskHC({ 
     applicationId: 'APP_ID', 
     apiKey: 'API_KEY', 
     subdomain:  'SUBDOMAIN', 
     analytics: false
   }); 
```

It is suggested that this work build on https://github.com/algolia/algoliasearch-zendesk/pull/74

**Comment by Jerska** [comment]
I've just release v2.24.0 .
You might want to change the external dependencies links as described in https://community.algolia.com/zendesk/documentation/#modifying-templates to invalidate the cache for the week to come.
