### ISSUE TITLE
How can I index also the private articles?

### ISSUE THREAD

**Issue by italodamato** [algolia/algoliasearch-zendesk#83]
I'd like to create a separate index which includes our agent-only articles from Zendesk. By default the connector takes only the public articles.

The idea is to switch indexes using the JS in the Zendesk theme:
if (HelpCenter.user.role == "agent" || HelpCenter.user.role == "manager") {
//use private index
}

Can you guide me through the process? I think it might be something in this file https://github.com/algolia/algoliasearch-zendesk/blob/master/crawler/types/user_segment.rb

**Comment by Jerska** [comment]
Hi! Unfortunately this would likely lead to the security issue which we're avoiding by only allowing public articles:
Indeed, switching based on a JavaScript variable means that technical users would be able to inspect the code and find the credentials and index name to use to access private articles.

If that's ok with you, you can run the connector yourself with `private: true` which will allow indexing both public and private articles:
- https://github.com/algolia/algoliasearch-zendesk/tree/master/crawler
- https://github.com/algolia/algoliasearch-zendesk/blob/master/crawler/config.rb

See also:
https://discourse.algolia.com/t/how-to-add-another-index-to-zendesk-search-for-employees-only/7177
